### ISSUE TITLE
No Video on Android Client

### ISSUE THREAD

**Issue by pchclx** [Veemyu/drc-sim-client-e#1]
Hello, I am running DRC-SIM Server successfully on a Ubuntu machine and can use the client locally on this same machine fine.  However when using the Android client, I can find my server and connect, however there is an issue. The audio comes through correctly but the screen stays on "Connected to backend .. waiting for server". Does not seem like controls go through either, just the audio.
Seems like I have everything set up right so not really sure. Would love to he able to use Android Client from the couch. Thanks for any help

**Comment by godofwrath** [comment]
I also have this problem, but it's not limited to android it propagates throughout all clients, after checking the logs it doesn't seem to receive any frame from the server, I even tried disabling the firewall entirely in case that was the cause, but it won't even work with the client local and the interface set as lo(cal). Same problem regardless of networking
